///////////////////////////////////////////////////////////////////////////////
// ControllerServices.h

#pragma once

#include "TcServices.h"

const ULONG DrvID_Controller = 0x3F000000;
#define SRVNAME_CONTROLLER "Controller"

///<AutoGeneratedContent id="ClassIDs">
const CTCID CID_ControllerCMain = {0xbd5e1bde,0xaeac,0x4bc0,{0xa8,0xe9,0xb6,0xf5,0x3d,0xec,0x86,0xc2}};
const CTCID CID_ControllerCGenerator = {0xdc6c6faa,0xe868,0x4ddc,{0x91,0x5c,0xf5,0x37,0xe7,0x40,0xee,0x1e}};
///</AutoGeneratedContent>

///<AutoGeneratedContent id="ParameterIDs">
const PTCID PID_MainDefaultAdsPort = 0x00000001;
const PTCID PID_MainCounter = 0x00000003;
const PTCID PID_GeneratorParameter = 0x00000001;
///</AutoGeneratedContent>

///<AutoGeneratedContent id="DataTypes">
#pragma pack(push,1)
typedef struct _MainInputs
{
	char GUI_Manager;
	float GUI_TargetPosition[8];
	USHORT GUI_ControlWord;
	LONG ActualPosition[6];
	USHORT StatusWord[6];
	bool GUI_StopingJog;
	SHORT GUI_JogDirection;
	bool GUI_MSelect[6];
	struct {
		unsigned char b_0 : 1;
		unsigned char b_1 : 1;
		unsigned char b_2 : 1;
		unsigned char b_3 : 1;
		unsigned char b_4 : 1;
		unsigned char b_5 : 1;
		unsigned char b_6 : 1;
		unsigned char b_7 : 1;
		unsigned char b_8 : 1;
		unsigned char b_9 : 1;
		unsigned char b_10 : 1;
		unsigned char b_11 : 1;
		unsigned char b_12 : 1;
		unsigned char b_13 : 1;
		unsigned char b_14 : 1;
		unsigned char b_15 : 1;
	} GUI_Ins;
	SHORT FeedOverride;
	char GUI_Pause;
} MainInputs, *PMainInputs;
#pragma pack(pop)

#pragma pack(push,1)
typedef struct _MainOutputs
{
	char GUI_GetNextCMD;
	LONG GUI_ActualPosition[6];
	LONG TargetPosition[6];
	USHORT ControlWord[6];
	char ModOfOperation;
	struct {
		unsigned char b_0 : 1;
		unsigned char b_1 : 1;
		unsigned char b_2 : 1;
		unsigned char b_3 : 1;
		unsigned char b_4 : 1;
		unsigned char b_5 : 1;
		unsigned char b_6 : 1;
		unsigned char b_7 : 1;
		unsigned char b_8 : 1;
		unsigned char b_9 : 1;
		unsigned char b_10 : 1;
		unsigned char b_11 : 1;
		unsigned char b_12 : 1;
		unsigned char b_13 : 1;
		unsigned char b_14 : 1;
		unsigned char b_15 : 1;
	} GUI_Outs;
	float Gui_Buff[100];
} MainOutputs, *PMainOutputs;
#pragma pack(pop)

typedef struct _GeneratorParameter
{
	ULONG data1;
	ULONG data2;
	double data3;
} GeneratorParameter, *PGeneratorParameter;

typedef struct _GeneratorInputs
{
	USHORT ErrorCodes[6];
	float Gui_Buff[100];
} GeneratorInputs, *PGeneratorInputs;

#pragma pack(push,1)
typedef struct _GeneratorOutputs
{
} GeneratorOutputs, *PGeneratorOutputs;
#pragma pack(pop)

///</AutoGeneratedContent>



///<AutoGeneratedContent id="DataAreaIDs">
#define ADI_MainInputs 0
#define ADI_MainOutputs 1
#define ADI_GeneratorInputs 0
#define ADI_GeneratorOutputs 1
///</AutoGeneratedContent>
